### ISSUE TITLE
Restore the history of GlowstonePlusPlus repository

### ISSUE THREAD

**Issue by jlirochon** [DragonetMC/Dragonet-Legacy#123]
For some reason, **DragonetMC/GlowstonePlusPlus** was not forked from **GlowstonePlusPlus/GlowstonePlusPlus**, but imported from a local copy of the code.

So we have practically no history, for example we can't compare or merge :disappointed_relieved:

Although it require some work, it should be possible to recreate this repository from a real GitHub fork, and reintegrate the stuff we changed in clear commits.

This way, we could benefit from upstream changes to GlowstonePlusPlus, and potentially contribute back if we fix some bugs.

**Comment by jlirochon** [comment]
I no one thinks it's a very bad idea, I think I can start working on this.

As I am new on the project, it's a good way to look at the stuff that were hooked on GlowstonePlusPlus

**Comment by ethsmith** [comment]
Would be a good idea, Glowstone++ will need to be up to date on dragonets side for it to be as efficient as possible cuz Dragonet functions on top of Glowstone++ and G++ being out of date means there's always chances of bugs being present that were already fixed

**Comment by DefinitlyEvil** [comment]
And please keep in mind that G++ is edited to be suitable for Dragonet. So I will fork original G++ and manually apply changes later today.

**Comment by jlirochon** [comment]
@DefinitlyEvil I already finished applying changes... I'm about to push this stuff...

**Comment by jlirochon** [comment]
Ok so I patched against master branch of GlowstonePlusPlus : https://github.com/jlirochon/GlowstonePlusPlus/commits/master

It builds, but when I run it, it exits after `[INFO] Loading DAPIS scripts...`

If you can take a look @DefinitlyEvil, I will sleep better (it's 2:40AM here)

**Comment by DefinitlyEvil** [comment]
@jlirochon Then you'd better go to sleep now, I still have some pieces of music to compose. ;)

**Comment by jlirochon** [comment]
For information I managed to remove Dragonet from Glowstone++ dependencies. Now Dragonet depends on Glowstone++, but not the other way.

**Comment by jlirochon** [comment]
And I did the fucking search & replace about private properties on translators.

**Comment by DefinitlyEvil** [comment]
Thx dude. ;D
